// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>The state the resource is currently in.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AddonsResourceState
    {
        [EnumMember(Value = "pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "provisioning")]
        #pragma warning disable CS1591
        Provisioning,
        #pragma warning restore CS1591
        [EnumMember(Value = "provisioned")]
        #pragma warning disable CS1591
        Provisioned,
        #pragma warning restore CS1591
        [EnumMember(Value = "deprovisioning")]
        #pragma warning disable CS1591
        Deprovisioning,
        #pragma warning restore CS1591
        [EnumMember(Value = "deprovisioned")]
        #pragma warning disable CS1591
        Deprovisioned,
        #pragma warning restore CS1591
        [EnumMember(Value = "provisioning-failed")]
        #pragma warning disable CS1591
        ProvisioningFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "deprovisioning-failed")]
        #pragma warning disable CS1591
        DeprovisioningFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "suspended")]
        #pragma warning disable CS1591
        Suspended,
        #pragma warning restore CS1591
    }
}
