// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>The data type of the metadata value.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AddonsAppMetadataType
    {
        [EnumMember(Value = "string")]
        #pragma warning disable CS1591
        StringValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "boolean")]
        #pragma warning disable CS1591
        Boolean,
        #pragma warning restore CS1591
    }
}
