// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AlertPolicyType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "v1/insights/droplet/load_1")]
        #pragma warning disable CS1591
        V1InsightsDropletLoad1,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/droplet/load_5")]
        #pragma warning disable CS1591
        V1InsightsDropletLoad5,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/droplet/load_15")]
        #pragma warning disable CS1591
        V1InsightsDropletLoad15,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/droplet/memory_utilization_percent")]
        #pragma warning disable CS1591
        V1InsightsDropletMemoryUtilizationPercent,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/droplet/disk_utilization_percent")]
        #pragma warning disable CS1591
        V1InsightsDropletDiskUtilizationPercent,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/droplet/cpu")]
        #pragma warning disable CS1591
        V1InsightsDropletCpu,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/droplet/disk_read")]
        #pragma warning disable CS1591
        V1InsightsDropletDiskRead,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/droplet/disk_write")]
        #pragma warning disable CS1591
        V1InsightsDropletDiskWrite,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/droplet/public_outbound_bandwidth")]
        #pragma warning disable CS1591
        V1InsightsDropletPublicOutboundBandwidth,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/droplet/public_inbound_bandwidth")]
        #pragma warning disable CS1591
        V1InsightsDropletPublicInboundBandwidth,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/droplet/private_outbound_bandwidth")]
        #pragma warning disable CS1591
        V1InsightsDropletPrivateOutboundBandwidth,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/droplet/private_inbound_bandwidth")]
        #pragma warning disable CS1591
        V1InsightsDropletPrivateInboundBandwidth,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/lbaas/avg_cpu_utilization_percent")]
        #pragma warning disable CS1591
        V1InsightsLbaasAvgCpuUtilizationPercent,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/lbaas/connection_utilization_percent")]
        #pragma warning disable CS1591
        V1InsightsLbaasConnectionUtilizationPercent,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/lbaas/droplet_health")]
        #pragma warning disable CS1591
        V1InsightsLbaasDropletHealth,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/lbaas/tls_connections_per_second_utilization_percent")]
        #pragma warning disable CS1591
        V1InsightsLbaasTlsConnectionsPerSecondUtilizationPercent,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/lbaas/increase_in_http_error_rate_percentage_5xx")]
        #pragma warning disable CS1591
        V1InsightsLbaasIncreaseInHttpErrorRatePercentage5Xx,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/lbaas/increase_in_http_error_rate_percentage_4xx")]
        #pragma warning disable CS1591
        V1InsightsLbaasIncreaseInHttpErrorRatePercentage4Xx,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/lbaas/increase_in_http_error_rate_count_5xx")]
        #pragma warning disable CS1591
        V1InsightsLbaasIncreaseInHttpErrorRateCount5Xx,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/lbaas/increase_in_http_error_rate_count_4xx")]
        #pragma warning disable CS1591
        V1InsightsLbaasIncreaseInHttpErrorRateCount4Xx,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/lbaas/high_http_request_response_time")]
        #pragma warning disable CS1591
        V1InsightsLbaasHighHttpRequestResponseTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/lbaas/high_http_request_response_time_50p")]
        #pragma warning disable CS1591
        V1InsightsLbaasHighHttpRequestResponseTime50P,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/lbaas/high_http_request_response_time_95p")]
        #pragma warning disable CS1591
        V1InsightsLbaasHighHttpRequestResponseTime95P,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/insights/lbaas/high_http_request_response_time_99p")]
        #pragma warning disable CS1591
        V1InsightsLbaasHighHttpRequestResponseTime99P,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/dbaas/alerts/load_15_alerts")]
        #pragma warning disable CS1591
        V1DbaasAlertsLoad15Alerts,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/dbaas/alerts/memory_utilization_alerts")]
        #pragma warning disable CS1591
        V1DbaasAlertsMemoryUtilizationAlerts,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/dbaas/alerts/disk_utilization_alerts")]
        #pragma warning disable CS1591
        V1DbaasAlertsDiskUtilizationAlerts,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/dbaas/alerts/cpu_alerts")]
        #pragma warning disable CS1591
        V1DbaasAlertsCpuAlerts,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/droplet/autoscale_alerts/current_instances")]
        #pragma warning disable CS1591
        V1DropletAutoscaleAlertsCurrentInstances,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/droplet/autoscale_alerts/target_instances")]
        #pragma warning disable CS1591
        V1DropletAutoscaleAlertsTargetInstances,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/droplet/autoscale_alerts/current_cpu_utilization")]
        #pragma warning disable CS1591
        V1DropletAutoscaleAlertsCurrentCpuUtilization,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/droplet/autoscale_alerts/target_cpu_utilization")]
        #pragma warning disable CS1591
        V1DropletAutoscaleAlertsTargetCpuUtilization,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/droplet/autoscale_alerts/current_memory_utilization")]
        #pragma warning disable CS1591
        V1DropletAutoscaleAlertsCurrentMemoryUtilization,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/droplet/autoscale_alerts/target_memory_utilization")]
        #pragma warning disable CS1591
        V1DropletAutoscaleAlertsTargetMemoryUtilization,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/droplet/autoscale_alerts/scale_up")]
        #pragma warning disable CS1591
        V1DropletAutoscaleAlertsScaleUp,
        #pragma warning restore CS1591
        [EnumMember(Value = "v1/droplet/autoscale_alerts/scale_down")]
        #pragma warning disable CS1591
        V1DropletAutoscaleAlertsScaleDown,
        #pragma warning restore CS1591
    }
}
