// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>Whether the candidate is a served model (serverless platform, a dedicateddeployment, or a model router) or an OHS-hosted agent config.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ApiCandidateModelSource
    {
        [EnumMember(Value = "CANDIDATE_MODEL_SOURCE_SERVERLESS")]
        #pragma warning disable CS1591
        CandidateModelSourceServerless,
        #pragma warning restore CS1591
        [EnumMember(Value = "CANDIDATE_MODEL_SOURCE_DEDICATED")]
        #pragma warning disable CS1591
        CandidateModelSourceDedicated,
        #pragma warning restore CS1591
        [EnumMember(Value = "CANDIDATE_MODEL_SOURCE_ROUTER")]
        #pragma warning disable CS1591
        CandidateModelSourceRouter,
        #pragma warning restore CS1591
        [EnumMember(Value = "CANDIDATE_MODEL_SOURCE_AGENT")]
        #pragma warning disable CS1591
        CandidateModelSourceAgent,
        #pragma warning restore CS1591
    }
}
