// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>
    /// Data to create a knowledge base data source
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiCreateKnowledgeBaseDataSourceInputPublic : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>AWS S3 Data Source</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiAwsDataSource? AwsDataSource { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiAwsDataSource AwsDataSource { get; set; }
#endif
        /// <summary>The chunking_algorithm property</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiChunkingAlgorithm? ChunkingAlgorithm { get; set; }
        /// <summary>The chunking_options property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiChunkingOptions? ChunkingOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiChunkingOptions ChunkingOptions { get; set; }
#endif
        /// <summary>Knowledge base id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? KnowledgeBaseUuid { get; set; }
#nullable restore
#else
        public string KnowledgeBaseUuid { get; set; }
#endif
        /// <summary>Spaces Bucket Data Source</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiSpacesDataSource? SpacesDataSource { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiSpacesDataSource SpacesDataSource { get; set; }
#endif
        /// <summary>WebCrawlerDataSource</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiWebCrawlerDataSource? WebCrawlerDataSource { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiWebCrawlerDataSource WebCrawlerDataSource { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiCreateKnowledgeBaseDataSourceInputPublic"/> and sets the default values.
        /// </summary>
        public ApiCreateKnowledgeBaseDataSourceInputPublic()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiCreateKnowledgeBaseDataSourceInputPublic"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiCreateKnowledgeBaseDataSourceInputPublic CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiCreateKnowledgeBaseDataSourceInputPublic();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aws_data_source", n => { AwsDataSource = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiAwsDataSource>(global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiAwsDataSource.CreateFromDiscriminatorValue); } },
                { "chunking_algorithm", n => { ChunkingAlgorithm = n.GetEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiChunkingAlgorithm>(); } },
                { "chunking_options", n => { ChunkingOptions = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiChunkingOptions>(global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiChunkingOptions.CreateFromDiscriminatorValue); } },
                { "knowledge_base_uuid", n => { KnowledgeBaseUuid = n.GetStringValue(); } },
                { "spaces_data_source", n => { SpacesDataSource = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiSpacesDataSource>(global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiSpacesDataSource.CreateFromDiscriminatorValue); } },
                { "web_crawler_data_source", n => { WebCrawlerDataSource = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiWebCrawlerDataSource>(global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiWebCrawlerDataSource.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiAwsDataSource>("aws_data_source", AwsDataSource);
            writer.WriteEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiChunkingAlgorithm>("chunking_algorithm", ChunkingAlgorithm);
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiChunkingOptions>("chunking_options", ChunkingOptions);
            writer.WriteStringValue("knowledge_base_uuid", KnowledgeBaseUuid);
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiSpacesDataSource>("spaces_data_source", SpacesDataSource);
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiWebCrawlerDataSource>("web_crawler_data_source", WebCrawlerDataSource);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
