// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>
    /// Per-phase progress for a model evaluation run. The candidate phase invokes thecandidate model once per dataset row; the judge phase scores eachcandidate-success row with the configured metrics. Counts grow as the runadvances; compare against total_rows to render a progress bar.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiModelEvaluationRunProgress : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Dataset rows whose candidate model call has completed (success or failure).</summary>
        public long? CandidateRowsEvaluated { get; set; }
        /// <summary>Candidate-success rows the judge has finished (scored or skipped). Caps atthe number of candidate successes, which may be below total_rows.</summary>
        public long? JudgeRowsEvaluated { get; set; }
        /// <summary>Total dataset rows for the run, sourced from the evaluation dataset.</summary>
        public long? TotalRows { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiModelEvaluationRunProgress"/> and sets the default values.
        /// </summary>
        public ApiModelEvaluationRunProgress()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiModelEvaluationRunProgress"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiModelEvaluationRunProgress CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiModelEvaluationRunProgress();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "candidate_rows_evaluated", n => { CandidateRowsEvaluated = n.GetLongValue(); } },
                { "judge_rows_evaluated", n => { JudgeRowsEvaluated = n.GetLongValue(); } },
                { "total_rows", n => { TotalRows = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("candidate_rows_evaluated", CandidateRowsEvaluated);
            writer.WriteLongValue("judge_rows_evaluated", JudgeRowsEvaluated);
            writer.WriteLongValue("total_rows", TotalRows);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
