// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>
    /// Model Evaluation Run Detail - full view returned when fetching a specific run.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiModelEvaluationRunDetail : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Inference configuration for the candidate model during evaluation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiCandidateInferenceConfig? CandidateInferenceConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiCandidateInferenceConfig CandidateInferenceConfig { get; set; }
#endif
        /// <summary>The candidate_model_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CandidateModelName { get; set; }
#nullable restore
#else
        public string CandidateModelName { get; set; }
#endif
        /// <summary>Whether inference runs against the serverless platform, a dedicated deployment, or a model router.</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiCandidateModelSource? CandidateModelSource { get; set; }
        /// <summary>Candidate model being evaluated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CandidateModelUuid { get; set; }
#nullable restore
#else
        public string CandidateModelUuid { get; set; }
#endif
        /// <summary>The completed_at property</summary>
        public DateTimeOffset? CompletedAt { get; set; }
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The dataset_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatasetName { get; set; }
#nullable restore
#else
        public string DatasetName { get; set; }
#endif
        /// <summary>Dataset used for the evaluation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatasetUuid { get; set; }
#nullable restore
#else
        public string DatasetUuid { get; set; }
#endif
        /// <summary>Error description if the run failed or partially succeeded.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorDescription { get; set; }
#nullable restore
#else
        public string ErrorDescription { get; set; }
#endif
        /// <summary>The eval_preset_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EvalPresetName { get; set; }
#nullable restore
#else
        public string EvalPresetName { get; set; }
#endif
        /// <summary>The eval_preset_uuid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EvalPresetUuid { get; set; }
#nullable restore
#else
        public string EvalPresetUuid { get; set; }
#endif
        /// <summary>UUID of the evaluation run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EvalRunUuid { get; set; }
#nullable restore
#else
        public string EvalRunUuid { get; set; }
#endif
        /// <summary>The judge_model_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JudgeModelName { get; set; }
#nullable restore
#else
        public string JudgeModelName { get; set; }
#endif
        /// <summary>Judge model used to score responses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JudgeModelUuid { get; set; }
#nullable restore
#else
        public string JudgeModelUuid { get; set; }
#endif
        /// <summary>Metrics selected for this evaluation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiEvaluationMetric>? Metrics { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiEvaluationMetric> Metrics { get; set; }
#endif
        /// <summary>Name of the evaluation run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Per-phase progress for a model evaluation run. The candidate phase invokes thecandidate model once per dataset row; the judge phase scores eachcandidate-success row with the configured metrics. Counts grow as the runadvances; compare against total_rows to render a progress bar.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiModelEvaluationRunProgress? Progress { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiModelEvaluationRunProgress Progress { get; set; }
#endif
        /// <summary>Aggregated result summary for a completed model evaluation run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiModelEvaluationRunResultSummary? ResultSummary { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiModelEvaluationRunResultSummary ResultSummary { get; set; }
#endif
        /// <summary>The star_metric property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiStarMetric? StarMetric { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiStarMetric StarMetric { get; set; }
#endif
        /// <summary>The started_at property</summary>
        public DateTimeOffset? StartedAt { get; set; }
        /// <summary>Model Evaluation Run Statuses</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiModelEvaluationRunStatus? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiModelEvaluationRunDetail"/> and sets the default values.
        /// </summary>
        public ApiModelEvaluationRunDetail()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiModelEvaluationRunDetail"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiModelEvaluationRunDetail CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiModelEvaluationRunDetail();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "candidate_inference_config", n => { CandidateInferenceConfig = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiCandidateInferenceConfig>(global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiCandidateInferenceConfig.CreateFromDiscriminatorValue); } },
                { "candidate_model_name", n => { CandidateModelName = n.GetStringValue(); } },
                { "candidate_model_source", n => { CandidateModelSource = n.GetEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiCandidateModelSource>(); } },
                { "candidate_model_uuid", n => { CandidateModelUuid = n.GetStringValue(); } },
                { "completed_at", n => { CompletedAt = n.GetDateTimeOffsetValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "dataset_name", n => { DatasetName = n.GetStringValue(); } },
                { "dataset_uuid", n => { DatasetUuid = n.GetStringValue(); } },
                { "error_description", n => { ErrorDescription = n.GetStringValue(); } },
                { "eval_preset_name", n => { EvalPresetName = n.GetStringValue(); } },
                { "eval_preset_uuid", n => { EvalPresetUuid = n.GetStringValue(); } },
                { "eval_run_uuid", n => { EvalRunUuid = n.GetStringValue(); } },
                { "judge_model_name", n => { JudgeModelName = n.GetStringValue(); } },
                { "judge_model_uuid", n => { JudgeModelUuid = n.GetStringValue(); } },
                { "metrics", n => { Metrics = n.GetCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiEvaluationMetric>(global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiEvaluationMetric.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "progress", n => { Progress = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiModelEvaluationRunProgress>(global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiModelEvaluationRunProgress.CreateFromDiscriminatorValue); } },
                { "result_summary", n => { ResultSummary = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiModelEvaluationRunResultSummary>(global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiModelEvaluationRunResultSummary.CreateFromDiscriminatorValue); } },
                { "star_metric", n => { StarMetric = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiStarMetric>(global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiStarMetric.CreateFromDiscriminatorValue); } },
                { "started_at", n => { StartedAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiModelEvaluationRunStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiCandidateInferenceConfig>("candidate_inference_config", CandidateInferenceConfig);
            writer.WriteStringValue("candidate_model_name", CandidateModelName);
            writer.WriteEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiCandidateModelSource>("candidate_model_source", CandidateModelSource);
            writer.WriteStringValue("candidate_model_uuid", CandidateModelUuid);
            writer.WriteDateTimeOffsetValue("completed_at", CompletedAt);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("dataset_name", DatasetName);
            writer.WriteStringValue("dataset_uuid", DatasetUuid);
            writer.WriteStringValue("error_description", ErrorDescription);
            writer.WriteStringValue("eval_preset_name", EvalPresetName);
            writer.WriteStringValue("eval_preset_uuid", EvalPresetUuid);
            writer.WriteStringValue("eval_run_uuid", EvalRunUuid);
            writer.WriteStringValue("judge_model_name", JudgeModelName);
            writer.WriteStringValue("judge_model_uuid", JudgeModelUuid);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiEvaluationMetric>("metrics", Metrics);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiModelEvaluationRunProgress>("progress", Progress);
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiModelEvaluationRunResultSummary>("result_summary", ResultSummary);
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiStarMetric>("star_metric", StarMetric);
            writer.WriteDateTimeOffsetValue("started_at", StartedAt);
            writer.WriteEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiModelEvaluationRunStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
