// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>Lifecycle status of a scenario set. Uploaded sets are created as ready.Generated sets start as generating and then become ready, failed, orcancelled. - SCENARIO_SET_STATUS_GENERATING: Generation is in progress. The scenarios are not ready yet. - SCENARIO_SET_STATUS_READY: The scenario set is ready to use. - SCENARIO_SET_STATUS_FAILED: Generation failed. The scenario set has no readable scenarios. - SCENARIO_SET_STATUS_CANCELLED: Generation was cancelled before completion.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ApiScenarioSetStatus
    {
        [EnumMember(Value = "SCENARIO_SET_STATUS_UNSPECIFIED")]
        #pragma warning disable CS1591
        ScenarioSetStatusUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCENARIO_SET_STATUS_GENERATING")]
        #pragma warning disable CS1591
        ScenarioSetStatusGenerating,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCENARIO_SET_STATUS_READY")]
        #pragma warning disable CS1591
        ScenarioSetStatusReady,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCENARIO_SET_STATUS_FAILED")]
        #pragma warning disable CS1591
        ScenarioSetStatusFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCENARIO_SET_STATUS_CANCELLED")]
        #pragma warning disable CS1591
        ScenarioSetStatusCancelled,
        #pragma warning restore CS1591
    }
}
