// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>The judge&apos;s verdict for a journey. - SIMULATION_JOURNEY_VERDICT_SUCCESS: The candidate agent satisfied the scenario&apos;s stopping criteria. - SIMULATION_JOURNEY_VERDICT_FAILURE: The candidate agent did not satisfy the stopping criteria. - SIMULATION_JOURNEY_VERDICT_INCONCLUSIVE: No conclusive verdict (e.g. max_turns reached without the judge finishing).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ApiSimulationJourneyVerdict
    {
        [EnumMember(Value = "SIMULATION_JOURNEY_VERDICT_UNSPECIFIED")]
        #pragma warning disable CS1591
        SimulationJourneyVerdictUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIMULATION_JOURNEY_VERDICT_SUCCESS")]
        #pragma warning disable CS1591
        SimulationJourneyVerdictSuccess,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIMULATION_JOURNEY_VERDICT_FAILURE")]
        #pragma warning disable CS1591
        SimulationJourneyVerdictFailure,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIMULATION_JOURNEY_VERDICT_INCONCLUSIVE")]
        #pragma warning disable CS1591
        SimulationJourneyVerdictInconclusive,
        #pragma warning restore CS1591
    }
}
