// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>
    /// A team-owned collection of scenarios.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiScenarioSet : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Object storage bucket holding the scenario file. Unset while status is generating.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BucketName { get; set; }
#nullable restore
#else
        public string BucketName { get; set; }
#endif
        /// <summary>Object storage bucket region. Unset while status is generating.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BucketRegion { get; set; }
#nullable restore
#else
        public string BucketRegion { get; set; }
#endif
        /// <summary>Time created at.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Time deleted at. Unset unless the scenario set has been deleted.</summary>
        public DateTimeOffset? DeletedAt { get; set; }
        /// <summary>Customer-supplied description.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Human-readable explanation of a terminal FAILED status. Empty otherwise.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FailureReason { get; set; }
#nullable restore
#else
        public string FailureReason { get; set; }
#endif
        /// <summary>Model that produced the scenarios. Only set for goal-generated scenario sets.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneratorModelUuid { get; set; }
#nullable restore
#else
        public string GeneratorModelUuid { get; set; }
#endif
        /// <summary>UUID of the source library entry. Only set for library scenario sets(`source_kind=SCENARIO_SET_SOURCE_KIND_LIBRARY`).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LibraryScenarioUuid { get; set; }
#nullable restore
#else
        public string LibraryScenarioUuid { get; set; }
#endif
        /// <summary>Customer-supplied name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Number of scenarios in the set. Unset while status is generating.</summary>
        public long? ScenarioCount { get; set; }
        /// <summary>UUID of the scenario set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScenarioSetUuid { get; set; }
#nullable restore
#else
        public string ScenarioSetUuid { get; set; }
#endif
        /// <summary>Signals export UUID that produced this set. Only set for signal-generatedscenario sets (`source_kind=SCENARIO_SET_SOURCE_KIND_SIGNAL_GENERATED`).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceExportId { get; set; }
#nullable restore
#else
        public string SourceExportId { get; set; }
#endif
        /// <summary>The goal that drove generation. Only set for goal_generated scenario sets.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceGoalDescription { get; set; }
#nullable restore
#else
        public string SourceGoalDescription { get; set; }
#endif
        /// <summary>How a scenario set was created. - SCENARIO_SET_SOURCE_KIND_USER_UPLOAD: Created from uploaded or inline scenarios. - SCENARIO_SET_SOURCE_KIND_GOAL_GENERATED: Produced by goal-driven generation. - SCENARIO_SET_SOURCE_KIND_LIBRARY: Copied from a platform-curated library entry. - SCENARIO_SET_SOURCE_KIND_SIGNAL_GENERATED: Produced from a completed Signals export.</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiScenarioSetSourceKind? SourceKind { get; set; }
        /// <summary>Object storage key for the scenario file. Unset while status is generating.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SpacesKey { get; set; }
#nullable restore
#else
        public string SpacesKey { get; set; }
#endif
        /// <summary>Lifecycle status of a scenario set. Uploaded sets are created as ready.Generated sets start as generating and then become ready, failed, orcancelled. - SCENARIO_SET_STATUS_GENERATING: Generation is in progress. The scenarios are not ready yet. - SCENARIO_SET_STATUS_READY: The scenario set is ready to use. - SCENARIO_SET_STATUS_FAILED: Generation failed. The scenario set has no readable scenarios. - SCENARIO_SET_STATUS_CANCELLED: Generation was cancelled before completion.</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiScenarioSetStatus? Status { get; set; }
        /// <summary>Time last updated at.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>Identifier of the generation workflow. Only set for goal-generated scenario sets.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowUuid { get; set; }
#nullable restore
#else
        public string WorkflowUuid { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiScenarioSet"/> and sets the default values.
        /// </summary>
        public ApiScenarioSet()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiScenarioSet"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiScenarioSet CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiScenarioSet();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bucket_name", n => { BucketName = n.GetStringValue(); } },
                { "bucket_region", n => { BucketRegion = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "deleted_at", n => { DeletedAt = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "failure_reason", n => { FailureReason = n.GetStringValue(); } },
                { "generator_model_uuid", n => { GeneratorModelUuid = n.GetStringValue(); } },
                { "library_scenario_uuid", n => { LibraryScenarioUuid = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "scenario_count", n => { ScenarioCount = n.GetLongValue(); } },
                { "scenario_set_uuid", n => { ScenarioSetUuid = n.GetStringValue(); } },
                { "source_export_id", n => { SourceExportId = n.GetStringValue(); } },
                { "source_goal_description", n => { SourceGoalDescription = n.GetStringValue(); } },
                { "source_kind", n => { SourceKind = n.GetEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiScenarioSetSourceKind>(); } },
                { "spaces_key", n => { SpacesKey = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiScenarioSetStatus>(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "workflow_uuid", n => { WorkflowUuid = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("bucket_name", BucketName);
            writer.WriteStringValue("bucket_region", BucketRegion);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteDateTimeOffsetValue("deleted_at", DeletedAt);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("failure_reason", FailureReason);
            writer.WriteStringValue("generator_model_uuid", GeneratorModelUuid);
            writer.WriteStringValue("library_scenario_uuid", LibraryScenarioUuid);
            writer.WriteStringValue("name", Name);
            writer.WriteLongValue("scenario_count", ScenarioCount);
            writer.WriteStringValue("scenario_set_uuid", ScenarioSetUuid);
            writer.WriteStringValue("source_export_id", SourceExportId);
            writer.WriteStringValue("source_goal_description", SourceGoalDescription);
            writer.WriteEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiScenarioSetSourceKind>("source_kind", SourceKind);
            writer.WriteStringValue("spaces_key", SpacesKey);
            writer.WriteEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ApiScenarioSetStatus>("status", Status);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteStringValue("workflow_uuid", WorkflowUuid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
