// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AppFunctionsSpec : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The alerts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppAlertSpec>? Alerts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppAlertSpec> Alerts { get; set; }
#endif
        /// <summary>The bitbucket property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.AppsBitbucketSourceSpec? Bitbucket { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.AppsBitbucketSourceSpec Bitbucket { get; set; }
#endif
        /// <summary>(Deprecated - Use Ingress Rules instead).</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.AppFunctionsSpecCors? Cors { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.AppFunctionsSpecCors Cors { get; set; }
#endif
        /// <summary>A list of environment variables made available to the component.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppVariableDefinition>? Envs { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppVariableDefinition> Envs { get; set; }
#endif
        /// <summary>The git property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.AppsGitSourceSpec? Git { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.AppsGitSourceSpec Git { get; set; }
#endif
        /// <summary>The github property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.AppsGithubSourceSpec? Github { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.AppsGithubSourceSpec Github { get; set; }
#endif
        /// <summary>The gitlab property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.AppsGitlabSourceSpec? Gitlab { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.AppsGitlabSourceSpec Gitlab { get; set; }
#endif
        /// <summary>A list of configured log forwarding destinations.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppLogDestinationDefinition>? LogDestinations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppLogDestinationDefinition> LogDestinations { get; set; }
#endif
        /// <summary>The name. Must be unique across all components within the same app.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>(Deprecated - Use Ingress Rules instead). A list of HTTP routes that should be routed to this component.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppRouteSpec>? Routes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppRouteSpec> Routes { get; set; }
#endif
        /// <summary>An optional path to the working directory to use for the build. For Dockerfile builds, this will be used as the build context. Must be relative to the root of the repo.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceDir { get; set; }
#nullable restore
#else
        public string SourceDir { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.AppFunctionsSpec"/> and sets the default values.
        /// </summary>
        public AppFunctionsSpec()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.AppFunctionsSpec"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DigitalOcean.OpenApiClient.Models.AppFunctionsSpec CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DigitalOcean.OpenApiClient.Models.AppFunctionsSpec();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alerts", n => { Alerts = n.GetCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppAlertSpec>(global::Soenneker.DigitalOcean.OpenApiClient.Models.AppAlertSpec.CreateFromDiscriminatorValue)?.AsList(); } },
                { "bitbucket", n => { Bitbucket = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppsBitbucketSourceSpec>(global::Soenneker.DigitalOcean.OpenApiClient.Models.AppsBitbucketSourceSpec.CreateFromDiscriminatorValue); } },
                { "cors", n => { Cors = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppFunctionsSpecCors>(global::Soenneker.DigitalOcean.OpenApiClient.Models.AppFunctionsSpecCors.CreateFromDiscriminatorValue); } },
                { "envs", n => { Envs = n.GetCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppVariableDefinition>(global::Soenneker.DigitalOcean.OpenApiClient.Models.AppVariableDefinition.CreateFromDiscriminatorValue)?.AsList(); } },
                { "git", n => { Git = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppsGitSourceSpec>(global::Soenneker.DigitalOcean.OpenApiClient.Models.AppsGitSourceSpec.CreateFromDiscriminatorValue); } },
                { "github", n => { Github = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppsGithubSourceSpec>(global::Soenneker.DigitalOcean.OpenApiClient.Models.AppsGithubSourceSpec.CreateFromDiscriminatorValue); } },
                { "gitlab", n => { Gitlab = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppsGitlabSourceSpec>(global::Soenneker.DigitalOcean.OpenApiClient.Models.AppsGitlabSourceSpec.CreateFromDiscriminatorValue); } },
                { "log_destinations", n => { LogDestinations = n.GetCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppLogDestinationDefinition>(global::Soenneker.DigitalOcean.OpenApiClient.Models.AppLogDestinationDefinition.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "routes", n => { Routes = n.GetCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppRouteSpec>(global::Soenneker.DigitalOcean.OpenApiClient.Models.AppRouteSpec.CreateFromDiscriminatorValue)?.AsList(); } },
                { "source_dir", n => { SourceDir = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppAlertSpec>("alerts", Alerts);
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppsBitbucketSourceSpec>("bitbucket", Bitbucket);
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppFunctionsSpecCors>("cors", Cors);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppVariableDefinition>("envs", Envs);
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppsGitSourceSpec>("git", Git);
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppsGithubSourceSpec>("github", Github);
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppsGitlabSourceSpec>("gitlab", Gitlab);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppLogDestinationDefinition>("log_destinations", LogDestinations);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.AppRouteSpec>("routes", Routes);
            writer.WriteStringValue("source_dir", SourceDir);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
