// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>
    /// Request body for creating a batch inference job.When `provider` is `openai`, `endpoint` is required and must be one of `/v1/responses` or `/v1/chat/completions`. When `provider` is `anthropic`, `endpoint` must be omitted — the Anthropic Message Batches API does not need a per-job endpoint.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BatchCreateRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The completion_window property</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.Value24HCompletionWindow? CompletionWindow { get; set; }
        /// <summary>Inference endpoint each request is dispatched to. **Required when `provider` is `openai` and must match the `url` on every JSONL line. Must be omitted when `provider` is `anthropic`.**</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.BatchCreateRequestEndpoint? Endpoint { get; set; }
        /// <summary>The `file_id` returned by `POST /v1/batches/files`.</summary>
        public Guid? FileId { get; set; }
        /// <summary>Optional string-valued metadata to attach to the job.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.BatchCreateRequestMetadataProperty? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.BatchCreateRequestMetadataProperty Metadata { get; set; }
#endif
        /// <summary>The inference provider whose JSONL schema the input file conforms to. `openai` follows the OpenAI Batch API input schema (`custom_id`, `method`, `url`, `body`); `anthropic` follows the Anthropic Message Batches JSONL conventions.</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.BatchCreateRequestProvider? Provider { get; set; }
        /// <summary>Client-supplied idempotency key. Retries with the same value return the existing job instead of creating a duplicate.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RequestId { get; set; }
#nullable restore
#else
        public string RequestId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.BatchCreateRequest"/> and sets the default values.
        /// </summary>
        public BatchCreateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.BatchCreateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DigitalOcean.OpenApiClient.Models.BatchCreateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DigitalOcean.OpenApiClient.Models.BatchCreateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "completion_window", n => { CompletionWindow = n.GetEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.Value24HCompletionWindow>(); } },
                { "endpoint", n => { Endpoint = n.GetEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.BatchCreateRequestEndpoint>(); } },
                { "file_id", n => { FileId = n.GetGuidValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.BatchCreateRequestMetadataProperty>(global::Soenneker.DigitalOcean.OpenApiClient.Models.BatchCreateRequestMetadataProperty.CreateFromDiscriminatorValue); } },
                { "provider", n => { Provider = n.GetEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.BatchCreateRequestProvider>(); } },
                { "request_id", n => { RequestId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.Value24HCompletionWindow>("completion_window", CompletionWindow);
            writer.WriteEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.BatchCreateRequestEndpoint>("endpoint", Endpoint);
            writer.WriteGuidValue("file_id", FileId);
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.BatchCreateRequestMetadataProperty>("metadata", Metadata);
            writer.WriteEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.BatchCreateRequestProvider>("provider", Provider);
            writer.WriteStringValue("request_id", RequestId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
