// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ByoipPrefixListResourcesResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ips property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.ByoipPrefixResource>? Ips { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.ByoipPrefixResource> Ips { get; set; }
#endif
        /// <summary>The links property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.PageLinks? Links { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.PageLinks Links { get; set; }
#endif
        /// <summary>The meta property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.MetaMeta? Meta { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.MetaMeta Meta { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.ByoipPrefixListResourcesResponse"/> and sets the default values.
        /// </summary>
        public ByoipPrefixListResourcesResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.ByoipPrefixListResourcesResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DigitalOcean.OpenApiClient.Models.ByoipPrefixListResourcesResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DigitalOcean.OpenApiClient.Models.ByoipPrefixListResourcesResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ips", n => { Ips = n.GetCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.ByoipPrefixResource>(global::Soenneker.DigitalOcean.OpenApiClient.Models.ByoipPrefixResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "links", n => { Links = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.PageLinks>(global::Soenneker.DigitalOcean.OpenApiClient.Models.PageLinks.CreateFromDiscriminatorValue); } },
                { "meta", n => { Meta = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.MetaMeta>(global::Soenneker.DigitalOcean.OpenApiClient.Models.MetaMeta.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.ByoipPrefixResource>("ips", Ips);
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.PageLinks>("links", Links);
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.MetaMeta>("meta", Meta);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
