// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChatCompletionRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model&apos;s likelihood to repeat the same line verbatim.</summary>
        public double? FrequencyPenalty { get; set; }
        /// <summary>Modify the likelihood of specified tokens appearing in the completion. Accepts a JSON object that maps tokens (specified by their token ID in the tokenizer) to an associated bias value from -100 to 100. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestLogitBiasProperty? LogitBias { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestLogitBiasProperty LogitBias { get; set; }
#endif
        /// <summary>Whether to return log probabilities of the output tokens or not. If true, returns the log probabilities of each output token returned in the content of message.</summary>
        public bool? Logprobs { get; set; }
        /// <summary>The maximum number of completion tokens that may be used over the course of the run. The run will make a best effort to use only the number of completion tokens specified, across multiple turns of the run.</summary>
        public int? MaxCompletionTokens { get; set; }
        /// <summary>The maximum number of tokens that can be generated in the completion. The token count of your prompt plus max_tokens cannot exceed the model&apos;s context length.</summary>
        public int? MaxTokens { get; set; }
        /// <summary>A list of messages comprising the conversation so far.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatMessage>? Messages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatMessage> Messages { get; set; }
#endif
        /// <summary>Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys are strings with a maximum length of 64 characters. Values are strings with a maximum length of 512 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestMetadataProperty? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestMetadataProperty Metadata { get; set; }
#endif
        /// <summary>Model ID used to generate the response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>How many chat completion choices to generate for each input message. Note that you will be charged based on the number of generated tokens across all of the choices. Keep n as 1 to minimize costs.</summary>
        public int? N { get; set; }
        /// <summary>Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model&apos;s likelihood to talk about new topics.</summary>
        public double? PresencePenalty { get; set; }
        /// <summary>Constrains effort on reasoning for reasoning models. Reducing reasoning effort can result in faster responses and fewer tokens used on reasoning in a response.</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestReasoningEffort? ReasoningEffort { get; set; }
        /// <summary>If specified, the system will make a best effort to sample deterministically, such that repeated requests with the same seed and parameters should return the same result. Determinism is not guaranteed.</summary>
        public int? Seed { get; set; }
        /// <summary>Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestStop? Stop { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestStop Stop { get; set; }
#endif
        /// <summary>If set to true, the model response data will be streamed to the client as it is generated using server-sent events.</summary>
        public bool? Stream { get; set; }
        /// <summary>Options for streaming response. Only set this when you set stream to true.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestStreamOptions? StreamOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestStreamOptions StreamOptions { get; set; }
#endif
        /// <summary>What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or top_p but not both.</summary>
        public double? Temperature { get; set; }
        /// <summary>Controls which (if any) tool is called by the model. none means the model will not call any tool and instead generates a message. auto means the model can pick between generating a message or calling one or more tools. required means the model must call one or more tools. Specifying a particular tool via {&quot;type&quot;: &quot;function&quot;, &quot;function&quot;: {&quot;name&quot;: &quot;my_function&quot;}} forces the model to call that tool. none is the default when no tools are present. auto is the default if tools are present.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestToolChoice? ToolChoice { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestToolChoice ToolChoice { get; set; }
#endif
        /// <summary>A list of tools the model may call. Currently, only functions are supported as a tool.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionTool>? Tools { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionTool> Tools { get; set; }
#endif
        /// <summary>An integer between 0 and 20 specifying the number of most likely tokens to return at each token position, each with an associated log probability. logprobs must be set to true if this parameter is used.</summary>
        public int? TopLogprobs { get; set; }
        /// <summary>An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered. We generally recommend altering this or temperature but not both.</summary>
        public double? TopP { get; set; }
        /// <summary>A unique identifier representing your end-user, which can help DigitalOcean to monitor and detect abuse.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? User { get; set; }
#nullable restore
#else
        public string User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequest"/> and sets the default values.
        /// </summary>
        public ChatCompletionRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            FrequencyPenalty = 0;
            Logprobs = false;
            N = 1;
            PresencePenalty = 0;
            Stream = false;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "frequency_penalty", n => { FrequencyPenalty = n.GetDoubleValue(); } },
                { "logit_bias", n => { LogitBias = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestLogitBiasProperty>(global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestLogitBiasProperty.CreateFromDiscriminatorValue); } },
                { "logprobs", n => { Logprobs = n.GetBoolValue(); } },
                { "max_completion_tokens", n => { MaxCompletionTokens = n.GetIntValue(); } },
                { "max_tokens", n => { MaxTokens = n.GetIntValue(); } },
                { "messages", n => { Messages = n.GetCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatMessage>(global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatMessage.CreateFromDiscriminatorValue)?.AsList(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestMetadataProperty>(global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestMetadataProperty.CreateFromDiscriminatorValue); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "n", n => { N = n.GetIntValue(); } },
                { "presence_penalty", n => { PresencePenalty = n.GetDoubleValue(); } },
                { "reasoning_effort", n => { ReasoningEffort = n.GetEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestReasoningEffort>(); } },
                { "seed", n => { Seed = n.GetIntValue(); } },
                { "stop", n => { Stop = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestStop>(global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestStop.CreateFromDiscriminatorValue); } },
                { "stream", n => { Stream = n.GetBoolValue(); } },
                { "stream_options", n => { StreamOptions = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestStreamOptions>(global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestStreamOptions.CreateFromDiscriminatorValue); } },
                { "temperature", n => { Temperature = n.GetDoubleValue(); } },
                { "tool_choice", n => { ToolChoice = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestToolChoice>(global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestToolChoice.CreateFromDiscriminatorValue); } },
                { "tools", n => { Tools = n.GetCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionTool>(global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionTool.CreateFromDiscriminatorValue)?.AsList(); } },
                { "top_logprobs", n => { TopLogprobs = n.GetIntValue(); } },
                { "top_p", n => { TopP = n.GetDoubleValue(); } },
                { "user", n => { User = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("frequency_penalty", FrequencyPenalty);
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestLogitBiasProperty>("logit_bias", LogitBias);
            writer.WriteBoolValue("logprobs", Logprobs);
            writer.WriteIntValue("max_completion_tokens", MaxCompletionTokens);
            writer.WriteIntValue("max_tokens", MaxTokens);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatMessage>("messages", Messages);
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestMetadataProperty>("metadata", Metadata);
            writer.WriteStringValue("model", Model);
            writer.WriteIntValue("n", N);
            writer.WriteDoubleValue("presence_penalty", PresencePenalty);
            writer.WriteEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestReasoningEffort>("reasoning_effort", ReasoningEffort);
            writer.WriteIntValue("seed", Seed);
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestStop>("stop", Stop);
            writer.WriteBoolValue("stream", Stream);
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestStreamOptions>("stream_options", StreamOptions);
            writer.WriteDoubleValue("temperature", Temperature);
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionRequestToolChoice>("tool_choice", ToolChoice);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.ChatCompletionTool>("tools", Tools);
            writer.WriteIntValue("top_logprobs", TopLogprobs);
            writer.WriteDoubleValue("top_p", TopP);
            writer.WriteStringValue("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
