// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>A string indicating the current status of the cluster.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ClusterReadStatusState
    {
        [EnumMember(Value = "running")]
        #pragma warning disable CS1591
        Running,
        #pragma warning restore CS1591
        [EnumMember(Value = "provisioning")]
        #pragma warning disable CS1591
        Provisioning,
        #pragma warning restore CS1591
        [EnumMember(Value = "degraded")]
        #pragma warning disable CS1591
        Degraded,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "deleted")]
        #pragma warning disable CS1591
        Deleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "upgrading")]
        #pragma warning disable CS1591
        Upgrading,
        #pragma warning restore CS1591
        [EnumMember(Value = "deleting")]
        #pragma warning disable CS1591
        Deleting,
        #pragma warning restore CS1591
    }
}
