// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>The type of action to initiate for the Droplet.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DropletActionType
    {
        [EnumMember(Value = "enable_backups")]
        #pragma warning disable CS1591
        EnableBackups,
        #pragma warning restore CS1591
        [EnumMember(Value = "disable_backups")]
        #pragma warning disable CS1591
        DisableBackups,
        #pragma warning restore CS1591
        [EnumMember(Value = "reboot")]
        #pragma warning disable CS1591
        Reboot,
        #pragma warning restore CS1591
        [EnumMember(Value = "power_cycle")]
        #pragma warning disable CS1591
        PowerCycle,
        #pragma warning restore CS1591
        [EnumMember(Value = "shutdown")]
        #pragma warning disable CS1591
        Shutdown,
        #pragma warning restore CS1591
        [EnumMember(Value = "power_off")]
        #pragma warning disable CS1591
        PowerOff,
        #pragma warning restore CS1591
        [EnumMember(Value = "power_on")]
        #pragma warning disable CS1591
        PowerOn,
        #pragma warning restore CS1591
        [EnumMember(Value = "restore")]
        #pragma warning disable CS1591
        Restore,
        #pragma warning restore CS1591
        [EnumMember(Value = "password_reset")]
        #pragma warning disable CS1591
        PasswordReset,
        #pragma warning restore CS1591
        [EnumMember(Value = "resize")]
        #pragma warning disable CS1591
        Resize,
        #pragma warning restore CS1591
        [EnumMember(Value = "rebuild")]
        #pragma warning disable CS1591
        Rebuild,
        #pragma warning restore CS1591
        [EnumMember(Value = "rename")]
        #pragma warning disable CS1591
        Rename,
        #pragma warning restore CS1591
        [EnumMember(Value = "change_kernel")]
        #pragma warning disable CS1591
        ChangeKernel,
        #pragma warning restore CS1591
        [EnumMember(Value = "enable_ipv6")]
        #pragma warning disable CS1591
        EnableIpv6,
        #pragma warning restore CS1591
        [EnumMember(Value = "snapshot")]
        #pragma warning disable CS1591
        Snapshot,
        #pragma warning restore CS1591
    }
}
