// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum InstanceSizeCpuType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "UNSPECIFIED")]
        #pragma warning disable CS1591
        Unspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "SHARED")]
        #pragma warning disable CS1591
        Shared,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEDICATED")]
        #pragma warning disable CS1591
        Dedicated,
        #pragma warning restore CS1591
    }
}
