// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>
    /// MCPExecution describes how to invoke a tool that is fronted by a remoteMCP server (as opposed to a plain HTTP endpoint). endpoint is the remoteMCP server&apos;s URL, tool_name is the name the remote server expects ontools/call (may differ from this tool&apos;s registry name), transportselects the wire protocol (&quot;streamable_http&quot; is the only kind implementedtoday), and server_ref is an opaque label identifying the remote serverfor logging/metrics/allowlisting.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class McpExecution : IParsable
    {
        /// <summary>The allowedHosts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AllowedHosts { get; set; }
#nullable restore
#else
        public List<string> AllowedHosts { get; set; }
#endif
        /// <summary>The endpoint property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Endpoint { get; set; }
#nullable restore
#else
        public string Endpoint { get; set; }
#endif
        /// <summary>The serverRef property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServerRef { get; set; }
#nullable restore
#else
        public string ServerRef { get; set; }
#endif
        /// <summary>The toolName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ToolName { get; set; }
#nullable restore
#else
        public string ToolName { get; set; }
#endif
        /// <summary>The transport property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Transport { get; set; }
#nullable restore
#else
        public string Transport { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.McpExecution"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DigitalOcean.OpenApiClient.Models.McpExecution CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DigitalOcean.OpenApiClient.Models.McpExecution();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowedHosts", n => { AllowedHosts = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "endpoint", n => { Endpoint = n.GetStringValue(); } },
                { "serverRef", n => { ServerRef = n.GetStringValue(); } },
                { "toolName", n => { ToolName = n.GetStringValue(); } },
                { "transport", n => { Transport = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("allowedHosts", AllowedHosts);
            writer.WriteStringValue("endpoint", Endpoint);
            writer.WriteStringValue("serverRef", ServerRef);
            writer.WriteStringValue("toolName", ToolName);
            writer.WriteStringValue("transport", Transport);
        }
    }
}
#pragma warning restore CS0618
