// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>
    /// Describes an MCP server to register.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class McpServerCreate : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>For `credentialRefSource` secret: the key or token itself. DigitalOcean stores it; it is write-only and no response returns it. Set exactly one of `credentialRef` and `api_key`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiKey { get; set; }
#nullable restore
#else
        public string ApiKey { get; set; }
#endif
        /// <summary>For `credentialRefSource` secret: a reference to a secret your team stores with DigitalOcean. Must match `^`[A-Za-z0-9]``[A-Za-z0-9:/_.-]`{0,254}$`. Set exactly one of `credentialRef` and `api_key`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CredentialRef { get; set; }
#nullable restore
#else
        public string CredentialRef { get; set; }
#endif
        /// <summary>How requests to the server authenticate: none (the default), secret, or connection. With secret, the value from `credentialRef` or `api_key` is sent in the Authorization header, prefixed with &quot;Bearer &quot; unless it already contains a space.</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.McpServerCreateCredentialRefSource? CredentialRefSource { get; set; }
        /// <summary>Optional description shown on the server&apos;s catalog card. At most 1024 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>HTTPS URL of the server&apos;s MCP endpoint. Its host must resolve only to public IP addresses. Required.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Endpoint { get; set; }
#nullable restore
#else
        public string Endpoint { get; set; }
#endif
        /// <summary>How long, in seconds, a user&apos;s authorization may be reused before they must consent again. Optional;0 means 30 days, and the maximum is 100 years.Authorizations are not refreshed automatically, so this window, not the provider&apos;s token lifetime,decides how often a user is sent back through consent. Set it no longer than the provider&apos;s owntoken lifetime, so the prompt arrives before a tool call fails against an expired token.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OauthAuthorizationTtlSeconds { get; set; }
#nullable restore
#else
        public string OauthAuthorizationTtlSeconds { get; set; }
#endif
        /// <summary>Required for `credentialRefSource` connection: the OAuth authorization endpoint. It must use the endpoint&apos;s scheme and port, on the endpoint&apos;s host or another host under the same registrable domain.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OauthAuthorizeUrl { get; set; }
#nullable restore
#else
        public string OauthAuthorizeUrl { get; set; }
#endif
        /// <summary>Required for `credentialRefSource` connection: the client ID of your team&apos;s OAuth client for the server. Each user of the server then authorizes individually.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OauthClientId { get; set; }
#nullable restore
#else
        public string OauthClientId { get; set; }
#endif
        /// <summary>Required for `credentialRefSource` connection. Write-only; no response returns it.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OauthClientSecret { get; set; }
#nullable restore
#else
        public string OauthClientSecret { get; set; }
#endif
        /// <summary>Required for `credentialRefSource` connection: the scopes to request from each user, 1 to 64 of them.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? OauthScopes { get; set; }
#nullable restore
#else
        public List<string> OauthScopes { get; set; }
#endif
        /// <summary>Required for `credentialRefSource` connection: the OAuth token endpoint, under the same rules as `oauth_authorize_url`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OauthTokenUrl { get; set; }
#nullable restore
#else
        public string OauthTokenUrl { get; set; }
#endif
        /// <summary>Identifier for the server, unique within your team. Must match `^`[a-z]``[a-z0-9-]`{0,63}$`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServerRef { get; set; }
#nullable restore
#else
        public string ServerRef { get; set; }
#endif
        /// <summary>Always `streamable_http`.</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.StreamableHttpTransport? Transport { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.McpServerCreate"/> and sets the default values.
        /// </summary>
        public McpServerCreate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.McpServerCreate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DigitalOcean.OpenApiClient.Models.McpServerCreate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DigitalOcean.OpenApiClient.Models.McpServerCreate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api_key", n => { ApiKey = n.GetStringValue(); } },
                { "credentialRef", n => { CredentialRef = n.GetStringValue(); } },
                { "credentialRefSource", n => { CredentialRefSource = n.GetEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.McpServerCreateCredentialRefSource>(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "endpoint", n => { Endpoint = n.GetStringValue(); } },
                { "oauth_authorization_ttl_seconds", n => { OauthAuthorizationTtlSeconds = n.GetStringValue(); } },
                { "oauth_authorize_url", n => { OauthAuthorizeUrl = n.GetStringValue(); } },
                { "oauth_client_id", n => { OauthClientId = n.GetStringValue(); } },
                { "oauth_client_secret", n => { OauthClientSecret = n.GetStringValue(); } },
                { "oauth_scopes", n => { OauthScopes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "oauth_token_url", n => { OauthTokenUrl = n.GetStringValue(); } },
                { "serverRef", n => { ServerRef = n.GetStringValue(); } },
                { "transport", n => { Transport = n.GetEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.StreamableHttpTransport>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("api_key", ApiKey);
            writer.WriteStringValue("credentialRef", CredentialRef);
            writer.WriteEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.McpServerCreateCredentialRefSource>("credentialRefSource", CredentialRefSource);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("endpoint", Endpoint);
            writer.WriteStringValue("oauth_authorization_ttl_seconds", OauthAuthorizationTtlSeconds);
            writer.WriteStringValue("oauth_authorize_url", OauthAuthorizeUrl);
            writer.WriteStringValue("oauth_client_id", OauthClientId);
            writer.WriteStringValue("oauth_client_secret", OauthClientSecret);
            writer.WriteCollectionOfPrimitiveValues<string>("oauth_scopes", OauthScopes);
            writer.WriteStringValue("oauth_token_url", OauthTokenUrl);
            writer.WriteStringValue("serverRef", ServerRef);
            writer.WriteEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.StreamableHttpTransport>("transport", Transport);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
