// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>The configured channel type. Allowed values:- `CHANNEL_TYPE_EMAIL` = email- `CHANNEL_TYPE_SLACK` = slack- `CHANNEL_TYPE_WEBHOOK` = webhook</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum NotificationChannelChannelType
    {
        [EnumMember(Value = "CHANNEL_TYPE_EMAIL")]
        #pragma warning disable CS1591
        ChannelTypeEmail,
        #pragma warning restore CS1591
        [EnumMember(Value = "CHANNEL_TYPE_SLACK")]
        #pragma warning disable CS1591
        ChannelTypeSlack,
        #pragma warning restore CS1591
        [EnumMember(Value = "CHANNEL_TYPE_WEBHOOK")]
        #pragma warning disable CS1591
        ChannelTypeWebhook,
        #pragma warning restore CS1591
    }
}
