// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>The health of the OpenSearch index.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OpensearchIndexHealth
    {
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "green")]
        #pragma warning disable CS1591
        Green,
        #pragma warning restore CS1591
        [EnumMember(Value = "yellow")]
        #pragma warning disable CS1591
        Yellow,
        #pragma warning restore CS1591
        [EnumMember(Value = "red")]
        #pragma warning disable CS1591
        Red,
        #pragma warning restore CS1591
        [EnumMember(Value = "red*")]
        #pragma warning disable CS1591
        RedAsterisk,
        #pragma warning restore CS1591
    }
}
