// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OptionsVersionAvailability : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An array of objects, each indicating the version end-of-life, end-of-availability for various database engines</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>? AdvancedMysql { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability> AdvancedMysql { get; set; }
#endif
        /// <summary>An array of objects, each indicating the version end-of-life, end-of-availability for various database engines</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>? AdvancedPg { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability> AdvancedPg { get; set; }
#endif
        /// <summary>An array of objects, each indicating the version end-of-life, end-of-availability for various database engines</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>? Kafka { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability> Kafka { get; set; }
#endif
        /// <summary>An array of objects, each indicating the version end-of-life, end-of-availability for various database engines</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>? Mongodb { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability> Mongodb { get; set; }
#endif
        /// <summary>An array of objects, each indicating the version end-of-life, end-of-availability for various database engines</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>? Mysql { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability> Mysql { get; set; }
#endif
        /// <summary>An array of objects, each indicating the version end-of-life, end-of-availability for various database engines</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>? Opensearch { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability> Opensearch { get; set; }
#endif
        /// <summary>An array of objects, each indicating the version end-of-life, end-of-availability for various database engines</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>? Pg { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability> Pg { get; set; }
#endif
        /// <summary>An array of objects, each indicating the version end-of-life, end-of-availability for various database engines</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>? Redis { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability> Redis { get; set; }
#endif
        /// <summary>An array of objects, each indicating the version end-of-life, end-of-availability for various database engines</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>? Valkey { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability> Valkey { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.OptionsVersionAvailability"/> and sets the default values.
        /// </summary>
        public OptionsVersionAvailability()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.OptionsVersionAvailability"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DigitalOcean.OpenApiClient.Models.OptionsVersionAvailability CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DigitalOcean.OpenApiClient.Models.OptionsVersionAvailability();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "advanced_mysql", n => { AdvancedMysql = n.GetCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>(global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability.CreateFromDiscriminatorValue)?.AsList(); } },
                { "advanced_pg", n => { AdvancedPg = n.GetCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>(global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability.CreateFromDiscriminatorValue)?.AsList(); } },
                { "kafka", n => { Kafka = n.GetCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>(global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability.CreateFromDiscriminatorValue)?.AsList(); } },
                { "mongodb", n => { Mongodb = n.GetCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>(global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability.CreateFromDiscriminatorValue)?.AsList(); } },
                { "mysql", n => { Mysql = n.GetCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>(global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability.CreateFromDiscriminatorValue)?.AsList(); } },
                { "opensearch", n => { Opensearch = n.GetCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>(global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability.CreateFromDiscriminatorValue)?.AsList(); } },
                { "pg", n => { Pg = n.GetCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>(global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability.CreateFromDiscriminatorValue)?.AsList(); } },
                { "redis", n => { Redis = n.GetCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>(global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability.CreateFromDiscriminatorValue)?.AsList(); } },
                { "valkey", n => { Valkey = n.GetCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>(global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>("advanced_mysql", AdvancedMysql);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>("advanced_pg", AdvancedPg);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>("kafka", Kafka);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>("mongodb", Mongodb);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>("mysql", Mysql);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>("opensearch", Opensearch);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>("pg", Pg);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>("redis", Redis);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.DatabaseVersionAvailability>("valkey", Valkey);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
