// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>
    /// Output view as your team sees it.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OutputView : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Null on a preview, which stores nothing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.OutputViewAudit? Audit { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.OutputViewAudit Audit { get; set; }
#endif
        /// <summary>View description.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The dotted output paths a projection keeps; arrays are traversed element-wise. Empty for a transform.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Fields { get; set; }
#nullable restore
#else
        public List<string> Fields { get; set; }
#endif
        /// <summary>`OUTPUT_VIEW_KIND_PROJECTION` or `OUTPUT_VIEW_KIND_TRANSFORM`.</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.OutputViewKind? Kind { get; set; }
        /// <summary>View name, unique per tool version among its owner&apos;s views.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The JSON Schema every result of this view satisfies.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.OutputViewOutputSchemaProperty? OutputSchema { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.OutputViewOutputSchemaProperty OutputSchema { get; set; }
#endif
        /// <summary>Your team&apos;s ID on your team&apos;s views, and empty for a view DigitalOcean publishes to every team.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TeamId { get; set; }
#nullable restore
#else
        public string TeamId { get; set; }
#endif
        /// <summary>The provider-qualified tool slug, for example `exa_search`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tool { get; set; }
#nullable restore
#else
        public string Tool { get; set; }
#endif
        /// <summary>The opaque identity of the exact tool version the view is bound to; tool and version are its readable coordinates.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ToolId { get; set; }
#nullable restore
#else
        public string ToolId { get; set; }
#endif
        /// <summary>The tool version, for example `v3`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>Output view ID, for example `ov_` followed by 32 hex digits. Empty on a preview.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ViewId { get; set; }
#nullable restore
#else
        public string ViewId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.OutputView"/> and sets the default values.
        /// </summary>
        public OutputView()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.OutputView"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DigitalOcean.OpenApiClient.Models.OutputView CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DigitalOcean.OpenApiClient.Models.OutputView();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "audit", n => { Audit = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.OutputViewAudit>(global::Soenneker.DigitalOcean.OpenApiClient.Models.OutputViewAudit.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "fields", n => { Fields = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "kind", n => { Kind = n.GetEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.OutputViewKind>(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "output_schema", n => { OutputSchema = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.OutputViewOutputSchemaProperty>(global::Soenneker.DigitalOcean.OpenApiClient.Models.OutputViewOutputSchemaProperty.CreateFromDiscriminatorValue); } },
                { "team_id", n => { TeamId = n.GetStringValue(); } },
                { "tool", n => { Tool = n.GetStringValue(); } },
                { "tool_id", n => { ToolId = n.GetStringValue(); } },
                { "version", n => { Version = n.GetStringValue(); } },
                { "view_id", n => { ViewId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.OutputViewAudit>("audit", Audit);
            writer.WriteStringValue("description", Description);
            writer.WriteCollectionOfPrimitiveValues<string>("fields", Fields);
            writer.WriteEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.OutputViewKind>("kind", Kind);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.OutputViewOutputSchemaProperty>("output_schema", OutputSchema);
            writer.WriteStringValue("team_id", TeamId);
            writer.WriteStringValue("tool", Tool);
            writer.WriteStringValue("tool_id", ToolId);
            writer.WriteStringValue("version", Version);
            writer.WriteStringValue("view_id", ViewId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
