// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>Record commit time of transactions.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostgresAdvancedConfigTrackCommitTimestamp
    {
        [EnumMember(Value = "off")]
        #pragma warning disable CS1591
        Off,
        #pragma warning restore CS1591
        [EnumMember(Value = "on")]
        #pragma warning disable CS1591
        On,
        #pragma warning restore CS1591
    }
}
