// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PrepaymentStatus : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Current prepayment balance. Decimal dollars, e.g. `&quot;25.00&quot;`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Balance { get; set; }
#nullable restore
#else
        public string Balance { get; set; }
#endif
        /// <summary>Whether the prepayment gate is currently blocking usage.</summary>
        public bool? Blocked { get; set; }
        /// <summary>Whether the account is eligible for the prepayment gate experience.</summary>
        public bool? Eligible { get; set; }
        /// <summary>Whether automatic prepayment top-up is enabled.</summary>
        public bool? IsAutoPrepayEnabled { get; set; }
        /// <summary>Current account balance including month-to-date usage. Decimal dollars, e.g. `&quot;75.00&quot;`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MonthToDateBalance { get; set; }
#nullable restore
#else
        public string MonthToDateBalance { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.PrepaymentStatus"/> and sets the default values.
        /// </summary>
        public PrepaymentStatus()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.PrepaymentStatus"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DigitalOcean.OpenApiClient.Models.PrepaymentStatus CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DigitalOcean.OpenApiClient.Models.PrepaymentStatus();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "balance", n => { Balance = n.GetStringValue(); } },
                { "blocked", n => { Blocked = n.GetBoolValue(); } },
                { "eligible", n => { Eligible = n.GetBoolValue(); } },
                { "is_auto_prepay_enabled", n => { IsAutoPrepayEnabled = n.GetBoolValue(); } },
                { "month_to_date_balance", n => { MonthToDateBalance = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("balance", Balance);
            writer.WriteBoolValue("blocked", Blocked);
            writer.WriteBoolValue("eligible", Eligible);
            writer.WriteBoolValue("is_auto_prepay_enabled", IsAutoPrepayEnabled);
            writer.WriteStringValue("month_to_date_balance", MonthToDateBalance);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
