// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>The type of the IPv6 network interface.**Note**: IPv6 private  networking is not currently supported.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PublicValueType
    {
        [EnumMember(Value = "public")]
        #pragma warning disable CS1591
        PublicValue,
        #pragma warning restore CS1591
    }
}
