// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>The slug of the subscription tier to sign up for.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RegistriesUpdateSubscriptionRequestTierSlug
    {
        [EnumMember(Value = "starter")]
        #pragma warning disable CS1591
        Starter,
        #pragma warning restore CS1591
        [EnumMember(Value = "basic")]
        #pragma warning disable CS1591
        Basic,
        #pragma warning restore CS1591
        [EnumMember(Value = "professional")]
        #pragma warning disable CS1591
        Professional,
        #pragma warning restore CS1591
    }
}
