// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>The type of action to initiate for the reserved IP.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ReservedIpActionTypeType
    {
        [EnumMember(Value = "assign")]
        #pragma warning disable CS1591
        Assign,
        #pragma warning restore CS1591
        [EnumMember(Value = "unassign")]
        #pragma warning disable CS1591
        Unassign,
        #pragma warning restore CS1591
    }
}
