// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>SessionPolicyAction is the disposition applied to a tool call. Lowercasevalues are canonical so ProtoJSON matches the public REST vocabulary; theprefixed aliases preserve compatibility for existing protobuf clients.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SessionPolicyAction
    {
        [EnumMember(Value = "allow")]
        #pragma warning disable CS1591
        Allow,
        #pragma warning restore CS1591
        [EnumMember(Value = "ask")]
        #pragma warning disable CS1591
        Ask,
        #pragma warning restore CS1591
        [EnumMember(Value = "deny")]
        #pragma warning disable CS1591
        Deny,
        #pragma warning restore CS1591
    }
}
