// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>
    /// SessionPolicyRule applies an action to a tool or version-pinned toolbelt.action must be allow, ask, or deny. match optionally narrows the rule tocalls with matching arguments.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SessionPolicyRule : IParsable
    {
        /// <summary>SessionPolicyAction is the disposition applied to a tool call. Lowercasevalues are canonical so ProtoJSON matches the public REST vocabulary; theprefixed aliases preserve compatibility for existing protobuf clients.</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.SessionPolicyAction? Action { get; set; }
        /// <summary>The match property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.SessionPolicyRuleMatchProperty? Match { get; set; }
#nullable restore
#else
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.SessionPolicyRuleMatchProperty Match { get; set; }
#endif
        /// <summary>The tool property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tool { get; set; }
#nullable restore
#else
        public string Tool { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.SessionPolicyRule"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DigitalOcean.OpenApiClient.Models.SessionPolicyRule CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DigitalOcean.OpenApiClient.Models.SessionPolicyRule();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.SessionPolicyAction>(); } },
                { "match", n => { Match = n.GetObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.SessionPolicyRuleMatchProperty>(global::Soenneker.DigitalOcean.OpenApiClient.Models.SessionPolicyRuleMatchProperty.CreateFromDiscriminatorValue); } },
                { "tool", n => { Tool = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.SessionPolicyAction>("action", Action);
            writer.WriteObjectValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.SessionPolicyRuleMatchProperty>("match", Match);
            writer.WriteStringValue("tool", Tool);
        }
    }
}
#pragma warning restore CS0618
