// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>
    /// Tool-permission policy of a session.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SessionPolicy : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Action for calls no rule matches. Empty means ask; otherwise this must be allow, ask, or deny.</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.Models.SessionPolicyDefaultAction? DefaultAction { get; set; }
        /// <summary>Rules for specific tools or toolbelts.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.SessionPolicyRulesItem>? Rules { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DigitalOcean.OpenApiClient.Models.SessionPolicyRulesItem> Rules { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DigitalOcean.OpenApiClient.Models.SessionPolicy"/> and sets the default values.
        /// </summary>
        public SessionPolicy()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "defaultAction", n => { DefaultAction = n.GetEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.SessionPolicyDefaultAction>(); } },
                { "rules", n => { Rules = n.GetCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.SessionPolicyRulesItem>(global::Soenneker.DigitalOcean.OpenApiClient.Models.SessionPolicyRulesItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.DigitalOcean.OpenApiClient.Models.SessionPolicyDefaultAction>("defaultAction", DefaultAction);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DigitalOcean.OpenApiClient.Models.SessionPolicyRulesItem>("rules", Rules);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
