// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TypeValue
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "application")]
        #pragma warning disable CS1591
        Application,
        #pragma warning restore CS1591
        [EnumMember(Value = "distribution")]
        #pragma warning disable CS1591
        Distribution,
        #pragma warning restore CS1591
    }
}
