// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>The role to assign to the user with each role mapping to a MongoDB built-in role.  `readOnly` maps to a [read](https://www.mongodb.com/docs/manual/reference/built-in-roles/#mongodb-authrole-read) role. `readWrite` maps to a [readWrite](https://www.mongodb.com/docs/manual/reference/built-in-roles/#mongodb-authrole-readWrite) role. `dbAdmin` maps to a [dbAdmin](https://www.mongodb.com/docs/manual/reference/built-in-roles/#mongodb-authrole-dbAdmin) role.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UserSettingsMongoUserSettingsRole
    {
        [EnumMember(Value = "readOnly")]
        #pragma warning disable CS1591
        ReadOnlyValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "readWrite")]
        #pragma warning disable CS1591
        ReadWrite,
        #pragma warning restore CS1591
        [EnumMember(Value = "dbAdmin")]
        #pragma warning disable CS1591
        DbAdmin,
        #pragma warning restore CS1591
    }
}
