// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.Models
{
    /// <summary>The current state of the VPC NAT gateway.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VpcNatGatewayGetState
    {
        [EnumMember(Value = "NEW")]
        #pragma warning disable CS1591
        NewValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROVISIONING")]
        #pragma warning disable CS1591
        Provisioning,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACTIVE")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "DELETING")]
        #pragma warning disable CS1591
        Deleting,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID")]
        #pragma warning disable CS1591
        Invalid,
        #pragma warning restore CS1591
    }
}
