// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Cpu_usage;
using Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Disk_usage;
using Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Index_vs_sequential_reads;
using Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Load;
using Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Memory_usage;
using Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Op_rates;
using Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Schema_latency;
using Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Schema_throughput;
using Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Threads_active;
using Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Threads_connected;
using Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Threads_created_rate;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\monitoring\metrics\database\mysql
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MysqlRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cpu_usage property</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Cpu_usage.Cpu_usageRequestBuilder Cpu_usage
        {
            get => new global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Cpu_usage.Cpu_usageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The disk_usage property</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Disk_usage.Disk_usageRequestBuilder Disk_usage
        {
            get => new global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Disk_usage.Disk_usageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The index_vs_sequential_reads property</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Index_vs_sequential_reads.Index_vs_sequential_readsRequestBuilder Index_vs_sequential_reads
        {
            get => new global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Index_vs_sequential_reads.Index_vs_sequential_readsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The load property</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Load.LoadRequestBuilder Load
        {
            get => new global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Load.LoadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The memory_usage property</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Memory_usage.Memory_usageRequestBuilder Memory_usage
        {
            get => new global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Memory_usage.Memory_usageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The op_rates property</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Op_rates.Op_ratesRequestBuilder Op_rates
        {
            get => new global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Op_rates.Op_ratesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The schema_latency property</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Schema_latency.Schema_latencyRequestBuilder Schema_latency
        {
            get => new global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Schema_latency.Schema_latencyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The schema_throughput property</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Schema_throughput.Schema_throughputRequestBuilder Schema_throughput
        {
            get => new global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Schema_throughput.Schema_throughputRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The threads_active property</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Threads_active.Threads_activeRequestBuilder Threads_active
        {
            get => new global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Threads_active.Threads_activeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The threads_connected property</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Threads_connected.Threads_connectedRequestBuilder Threads_connected
        {
            get => new global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Threads_connected.Threads_connectedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The threads_created_rate property</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Threads_created_rate.Threads_created_rateRequestBuilder Threads_created_rate
        {
            get => new global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.Threads_created_rate.Threads_created_rateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.MysqlRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MysqlRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/monitoring/metrics/database/mysql", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DigitalOcean.OpenApiClient.V2.Monitoring.Metrics.Database.Mysql.MysqlRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MysqlRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/monitoring/metrics/database/mysql", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
