// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.DigitalOcean.OpenApiClient.V2.Registry.Item.Repositories.Item.Digests;
using Soenneker.DigitalOcean.OpenApiClient.V2.Registry.Item.Repositories.Item.Tags;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.DigitalOcean.OpenApiClient.V2.Registry.Item.Repositories.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\registry\{registryName}\repositories\{repositoryName}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithRepositoryNameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The digests property</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.V2.Registry.Item.Repositories.Item.Digests.DigestsRequestBuilder Digests
        {
            get => new global::Soenneker.DigitalOcean.OpenApiClient.V2.Registry.Item.Repositories.Item.Digests.DigestsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tags property</summary>
        public global::Soenneker.DigitalOcean.OpenApiClient.V2.Registry.Item.Repositories.Item.Tags.TagsRequestBuilder Tags
        {
            get => new global::Soenneker.DigitalOcean.OpenApiClient.V2.Registry.Item.Repositories.Item.Tags.TagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DigitalOcean.OpenApiClient.V2.Registry.Item.Repositories.Item.WithRepositoryNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRepositoryNameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/registry/{registryName}/repositories/{repositoryName}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DigitalOcean.OpenApiClient.V2.Registry.Item.Repositories.Item.WithRepositoryNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRepositoryNameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/registry/{registryName}/repositories/{repositoryName}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
